### ISSUE TITLE
Status-message project test failed from clean state

### ISSUE THREAD

**Issue by k06a** [nearprotocol/near-bindgen#17]
```bash
$ RUST_BACKTRACE=1 cargo test --package status-message --features env_test
```

```bash
Compiling libc v0.2.60
   Compiling crc32fast v1.2.0
   Compiling proc-macro2 v0.4.30
   Compiling cfg-if v0.1.9
   Compiling unicode-xid v0.1.0
   Compiling rle-decode-fast v1.0.1
   Compiling take_mut v0.2.2
   Compiling adler32 v1.0.3
   Compiling syn v0.15.39
   Compiling cc v1.0.41
   Compiling pkg-config v0.3.15
   Compiling serde v1.0.97
   Compiling ryu v1.0.0
   Compiling wee_alloc v0.4.5
   Compiling bs58 v0.2.4
   Compiling itoa v0.4.4
   Compiling memory_units v0.4.0
   Compiling lazy_static v1.4.0
   Compiling libflate v0.1.27
   Compiling filetime v0.2.7
   Compiling xattr v0.2.2
   Compiling quote v0.6.13
   Compiling tar v0.4.26
   Compiling libsodium-sys v0.2.2
   Compiling borsh-derive-internal v0.2.1
   Compiling near-bindgen-core v0.2.2 (/Users/k06a/Projects/near-bindgen/near-bindgen-core)
   Compiling serde_derive v1.0.97
   Compiling borsh-derive v0.2.1
   Compiling near-bindgen-macros v0.2.2 (/Users/k06a/Projects/near-bindgen/near-bindgen-macros)
   Compiling borsh v0.2.1
   Compiling near-runtime-fees v0.2.1
   Compiling serde_json v1.0.40
   Compiling sodiumoxide v0.2.2
   Compiling near-vm-logic v0.2.3
   Compiling near-bindgen v0.2.2 (/Users/k06a/Projects/near-bindgen/near-bindgen)
   Compiling status-message v0.1.0 (/Users/k06a/Projects/near-bindgen/examples/status-message)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 12s
     Running target/debug/deps/status_message-46bd16e624805d89

running 2 tests
test tests::get_nonexistent_message ... ok
test tests::set_get_message ... FAILED

failures:

---- tests::set_get_message stdout ----
thread 'tests::set_get_message' panicked at 'Register was expected to have data because we just wrote it into it.', src/libcore/option.rs:1190:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:61
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:45
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/io/mod.rs:1412
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:141
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:48
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:33
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:211
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
  13: rust_begin_unwind
             at src/libstd/panicking.rs:311
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  15: core::option::expect_failed
             at src/libcore/option.rs:1190
  16: core::option::Option<T>::expect
             at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libcore/option.rs:345
  17: near_bindgen::environment::env::signer_account_id
             at /Users/k06a/Projects/near-bindgen/near-bindgen/src/environment/env.rs:95
  18: status_message::StatusMessage::set_status
             at src/lib.rs:18
  19: status_message::tests::set_get_message
             at src/lib.rs:58
  20: status_message::tests::set_get_message::{{closure}}
             at src/lib.rs:53
  21: core::ops::function::FnOnce::call_once
             at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libcore/ops/function.rs:227
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/liballoc/boxed.rs:922
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  24: std::panicking::try
             at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/panicking.rs:275
  25: std::panic::catch_unwind
             at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/panic.rs:394
  26: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1413
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::set_get_message

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p status-message --lib'
```

```bash
$ RUST_BACKTRACE=full cargo test --package status-message --features env_test
```

```bash
   Compiling libc v0.2.60
   Compiling proc-macro2 v0.4.30
   Compiling crc32fast v1.2.0
   Compiling unicode-xid v0.1.0
   Compiling cfg-if v0.1.9
   Compiling adler32 v1.0.3
   Compiling take_mut v0.2.2
   Compiling rle-decode-fast v1.0.1
   Compiling syn v0.15.39
   Compiling cc v1.0.41
   Compiling pkg-config v0.3.15
   Compiling serde v1.0.97
   Compiling ryu v1.0.0
   Compiling wee_alloc v0.4.5
   Compiling bs58 v0.2.4
   Compiling memory_units v0.4.0
   Compiling itoa v0.4.4
   Compiling lazy_static v1.4.0
   Compiling libflate v0.1.27
   Compiling quote v0.6.13
   Compiling filetime v0.2.7
   Compiling xattr v0.2.2
   Compiling tar v0.4.26
   Compiling libsodium-sys v0.2.2
   Compiling borsh-derive-internal v0.2.1
   Compiling near-bindgen-core v0.2.2 (/Users/k06a/Projects/near-bindgen/near-bindgen-core)
   Compiling serde_derive v1.0.97
   Compiling borsh-derive v0.2.1
   Compiling near-bindgen-macros v0.2.2 (/Users/k06a/Projects/near-bindgen/near-bindgen-macros)
   Compiling borsh v0.2.1
   Compiling near-runtime-fees v0.2.1
   Compiling serde_json v1.0.40
   Compiling sodiumoxide v0.2.2
   Compiling near-vm-logic v0.2.3
   Compiling near-bindgen v0.2.2 (/Users/k06a/Projects/near-bindgen/near-bindgen)
   Compiling status-message v0.1.0 (/Users/k06a/Projects/near-bindgen/examples/status-message)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 22s
     Running target/debug/deps/status_message-46bd16e624805d89

running 2 tests
test tests::get_nonexistent_message ... ok
test tests::set_get_message ... FAILED

failures:

---- tests::set_get_message stdout ----
thread 'tests::set_get_message' panicked at 'Register was expected to have data because we just wrote it into it.', src/libcore/option.rs:1190:5
stack backtrace:
   0:        0x100ab04fc - backtrace::backtrace::libunwind::trace::ha541e1bc74dbe7dc
                               at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:        0x100ab04fc - backtrace::backtrace::trace_unsynchronized::h8371015938fcff89
                               at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:        0x100ab04fc - std::sys_common::backtrace::_print_fmt::h4a16805c95a7dd53
                               at src/libstd/sys_common/backtrace.rs:61
   3:        0x100ab04fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e21874e6a894a83
                               at src/libstd/sys_common/backtrace.rs:45
   4:        0x100aca580 - core::fmt::write::h86e4be7336e0b09c
                               at src/libcore/fmt/mod.rs:1030
   5:        0x100a02aa9 - std::io::Write::write_fmt::h060fc01673d15a33
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/io/mod.rs:1412
   6:        0x100aabf1c - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::he1e3aedce15eeb66
                               at src/libstd/io/impls.rs:141
   7:        0x100ab20dd - std::sys_common::backtrace::_print::h84a78bc34f92dda2
                               at src/libstd/sys_common/backtrace.rs:48
   8:        0x100ab20dd - std::sys_common::backtrace::print::hc4c7ed85ff8cea8b
                               at src/libstd/sys_common/backtrace.rs:33
   9:        0x100ab20dd - std::panicking::default_hook::{{closure}}::hf5beb31afcd84982
                               at src/libstd/panicking.rs:200
  10:        0x100ab1d83 - std::panicking::default_hook::h0f94b02abe85cace
                               at src/libstd/panicking.rs:211
  11:        0x100ab2827 - std::panicking::rust_panic_with_hook::h8bc7d846a0025752
                               at src/libstd/panicking.rs:477
  12:        0x100ab236d - std::panicking::continue_panic_fmt::h67171a0a732f962e
                               at src/libstd/panicking.rs:384
  13:        0x100ab2269 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
  14:        0x100ac7a0f - core::panicking::panic_fmt::h4329b659c9b85d91
                               at src/libcore/panicking.rs:85
  15:        0x100ac7a6e - core::option::expect_failed::hc190722a05bb9353
                               at src/libcore/option.rs:1190
  16:        0x100a400fe - core::option::Option<T>::expect::h85ad914131b99b86
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libcore/option.rs:345
  17:        0x100a428a0 - near_bindgen::environment::env::signer_account_id::h5ccc2bddb2c39c4b
                               at /Users/k06a/Projects/near-bindgen/near-bindgen/src/environment/env.rs:95
  18:        0x1009f74e7 - status_message::StatusMessage::set_status::hcf6fe63f4b936f76
                               at src/lib.rs:18
  19:        0x1009fa633 - status_message::tests::set_get_message::h3ccc1276836f4c58
                               at src/lib.rs:58
  20:        0x1009f92c1 - status_message::tests::set_get_message::{{closure}}::h83bdf38ac36c8be0
                               at src/lib.rs:53
  21:        0x1009f6591 - core::ops::function::FnOnce::call_once::h148c6ca996b57518
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libcore/ops/function.rs:227
  22:        0x100a0cc1e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hca3424fa963c6b76
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/liballoc/boxed.rs:922
  23:        0x100ab46ef - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  24:        0x100a266f7 - std::panicking::try::hf6110f214442151f
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/panicking.rs:275
  25:        0x100a266f7 - std::panic::catch_unwind::he1ffea0554aff702
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/panic.rs:394
  26:        0x100a266f7 - test::run_test::run_test_inner::{{closure}}::h1c9613202a5ed23d
                               at src/libtest/lib.rs:1413
  27:        0x100a02255 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb580b1ea0df1c794
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/sys_common/backtrace.rs:114
  28:        0x100a06405 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hb85199980dd23ae2
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/thread/mod.rs:470
  29:        0x100a06405 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc78f38a3e45e9d73
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/panic.rs:315
  30:        0x100a06405 - std::panicking::try::do_call::h50049a1b2ffba3b0
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/panicking.rs:296
  31:        0x100ab46ef - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  32:        0x100a06985 - std::panicking::try::hdac98c59c865b667
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/panicking.rs:275
  33:        0x100a06985 - std::panic::catch_unwind::h33dc58b4a519af4e
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/panic.rs:394
  34:        0x100a06985 - std::thread::Builder::spawn_unchecked::{{closure}}::h262bee4387cebc9d
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libstd/thread/mod.rs:469
  35:        0x100a06985 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h09ebf5fee9cc9a4c
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/libcore/ops/function.rs:227
  36:        0x100aa8b9e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h261f9f17a8661ad4
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/liballoc/boxed.rs:922
  37:        0x100ab410e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::haf9b1b18aaaab823
                               at /rustc/2b8116dced2c6c5d02e1c4359e89dc0919d6001b/src/liballoc/boxed.rs:922
  38:        0x100ab410e - std::sys_common::thread::start_thread::hbba75d4e459ee59a
                               at src/libstd/sys_common/thread.rs:13
  39:        0x100ab410e - std::sys::unix::thread::Thread::new::thread_start::h0c2494b2cab31647
                               at src/libstd/sys/unix/thread.rs:79
  40:     0x7fff66e2d2eb - <unknown>
  41:     0x7fff66e30249 - <unknown>


failures:
    tests::set_get_message

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p status-message --lib'
```

**Comment by nearmax** [comment]
Cannot reproduce with the current code.
